# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: spud_test_app
  username: root
  
test:
  adapter: mysql2
  database: spud_test_app_test
  username: root

